# Generated by Django 6.0.4 on 2026-05-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
