# Generated by Django 4.2 on 2026-05-11 22:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('client_nom', models.CharField(max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_preparation', 'En préparation'), ('en_livraison', 'En livraison'), ('livree', 'Livré'), ('annulee', 'Annulé')], default='en_attente', max_length=20)),
                ('livree_le', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_entreprise/')),
                ('telephone', models.CharField(blank=True, default='', max_length=20)),
                ('adresse', models.CharField(blank=True, default='', max_length=300)),
                ('horaire_ouverture', models.TimeField(default=datetime.time(8, 0))),
                ('horaire_fermeture', models.TimeField(default=datetime.time(23, 0))),
                ('est_ouvert', models.BooleanField(default=True)),
                ('est_suspendu', models.BooleanField(default=False, help_text='Suspendu par l’admin Swift (différent de la fermeture horaire).')),
                ('en_ligne', models.BooleanField(default=False)),
                ('taux_acceptation', models.FloatField(default=96.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TicketSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('resolu', 'Résolu')], default='ouvert', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_support', to='entreprise.entreprise')),
            ],
            options={
                'verbose_name': 'Ticket support',
                'verbose_name_plural': 'Tickets support',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProduitCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8)),
                ('categorie', models.CharField(blank=True, default='', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits_catalogue/')),
                ('disponible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_catalogue', to='entreprise.entreprise')),
            ],
            options={
                'verbose_name': 'Produit catalogue',
                'verbose_name_plural': 'Produits catalogue',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('commentaire', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='entreprise.commande')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
            },
        ),
        migrations.AddField(
            model_name='commande',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='entreprise.entreprise'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['entreprise', '-created_at'], name='entreprise__entrepr_5c8584_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['entreprise', 'statut'], name='entreprise__entrepr_2954ca_idx'),
        ),
    ]
