# Generated by Django 6.0.4 on 2026-05-08 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entreprise', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=191, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('vehicle_type', models.CharField(choices=[('voiture', 'Voiture'), ('moto', 'Moto')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_assignment', to='entreprise.commande')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='driver.driver')),
            ],
        ),
        migrations.CreateModel(
            name='DriverRejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_rejections', to='entreprise.commande')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejections', to='driver.driver')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('driver', 'commande'), name='unique_driver_commande_rejection')],
            },
        ),
    ]
