# Generated by Django 6.0.4 on 2026-05-08 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverClientOrderRejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_order_rejections', to='driver.driver')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swift_driver_rejections', to='orders.order')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('driver', 'order'), name='unique_swift_driver_client_order_rejection')],
            },
        ),
    ]
