# Generated by Django 6.0.4 on 2026-05-09 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_swift_client_order_ws'),
        ('orders', '0003_swift_client_order_ws'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='vehicle_type',
            new_name='vehicle',
        ),
        migrations.CreateModel(
            name='DriverOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('current', 'current'), ('delivered', 'delivered'), ('rejected', 'rejected')], default='current', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_orders', to='driver.driver')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_order_rows', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('driver', 'order'), name='unique_driver_client_order_row')],
            },
        ),
    ]
