# Generated by Django 4.2 on 2026-05-11 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_vehicle_and_driver_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='compte_statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('suspendu', 'Suspendu')], db_index=True, default='valide', max_length=20),
        ),
    ]
