# Generated by Django 4.2 on 2026-05-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=20)),
                ('mot_de_passe', models.CharField(max_length=255)),
                ('en_ligne', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('en_livraison', 'En livraison'), ('hors_ligne', 'Hors ligne')], default='hors_ligne', max_length=20)),
                ('note_moyenne', models.FloatField(default=0)),
                ('total_notes', models.IntegerField(default=0)),
                ('somme_notes', models.IntegerField(default=0)),
                ('valide', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
