# Generated by Django 4.2 on 2026-05-07 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sw', models.CharField(max_length=20, unique=True)),
                ('articles', models.JSONField(default=list)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frais_livraison', models.DecimalField(decimal_places=2, default=2.99, max_digits=6)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_preparation', 'En préparation'), ('en_livraison', 'En livraison'), ('livree', 'Livrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('adresse_livraison', models.JSONField(default=dict)),
                ('evaluation_note', models.IntegerField(blank=True, null=True)),
                ('evaluation_comment', models.TextField(blank=True)),
                ('acceptee_at', models.DateTimeField(blank=True, null=True)),
                ('livree_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
