# Generated by Django 4.2 on 2026-05-07 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
        ('entreprise', '0001_initial'),
        ('livreurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='entreprise.entreprise'),
        ),
        migrations.AddField(
            model_name='commande',
            name='livreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='livreurs.livreur'),
        ),
    ]
