from django.urls import path

from .admin_swift_api import (
    SwiftAdminClientDeleteView,
    SwiftAdminClientHistoryView,
    SwiftAdminClientsListView,
    SwiftAdminDashboardStatsView,
    SwiftAdminEntrepriseActivateView,
    SwiftAdminEntrepriseHistoryView,
    SwiftAdminEntreprisesListView,
    SwiftAdminEntrepriseSuspendView,
    SwiftAdminLivreurHistoryView,
    SwiftAdminLivreursListView,
    SwiftAdminLivreurSuspendreView,
    SwiftAdminLivreurValiderView,
)
from .views import (
    AdminDashboardView,
    CurrentUserView,
    LoginView,
    LogoutView,
    PrincipalAdminChangePasswordView,
    PrincipalAdminLoginView,
    RegisterView,
    login_page,
    role_dashboard,
)

urlpatterns = [
    path('app/login', login_page, name='login-page'),
    path('app/dashboard', role_dashboard, name='role-dashboard'),
    path('register', RegisterView.as_view(), name='register'),
    path('login', LoginView.as_view(), name='login'),
    path('swift-admin/principal-login', PrincipalAdminLoginView.as_view(), name='swift-principal-admin-login'),
    path('swift-admin/change-password', PrincipalAdminChangePasswordView.as_view(), name='swift-principal-admin-password'),
    path('swift-admin/dashboard-stats', SwiftAdminDashboardStatsView.as_view(), name='swift-admin-dashboard-stats'),
    path('swift-admin/clients/<int:pk>/historique', SwiftAdminClientHistoryView.as_view(), name='swift-admin-client-historique'),
    path('swift-admin/clients/<int:pk>', SwiftAdminClientDeleteView.as_view(), name='swift-admin-client-delete'),
    path('swift-admin/clients', SwiftAdminClientsListView.as_view(), name='swift-admin-clients'),
    path('swift-admin/entreprises/<int:pk>/historique', SwiftAdminEntrepriseHistoryView.as_view(), name='swift-admin-entreprise-historique'),
    path('swift-admin/entreprises/<int:pk>/valider', SwiftAdminEntrepriseActivateView.as_view(), name='swift-admin-entreprise-valider'),
    path('swift-admin/entreprises/<int:pk>/suspendre', SwiftAdminEntrepriseSuspendView.as_view(), name='swift-admin-entreprise-suspendre'),
    path('swift-admin/entreprises', SwiftAdminEntreprisesListView.as_view(), name='swift-admin-entreprises'),
    path('swift-admin/livreurs/<int:pk>/historique', SwiftAdminLivreurHistoryView.as_view(), name='swift-admin-livreur-historique'),
    path('swift-admin/livreurs/<int:pk>/valider', SwiftAdminLivreurValiderView.as_view(), name='swift-admin-livreur-valider'),
    path('swift-admin/livreurs/<int:pk>/suspendre', SwiftAdminLivreurSuspendreView.as_view(), name='swift-admin-livreur-suspendre'),
    path('swift-admin/livreurs', SwiftAdminLivreursListView.as_view(), name='swift-admin-livreurs'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('me', CurrentUserView.as_view(), name='current-user'),
    path('dashboard', AdminDashboardView.as_view(), name='admin-dashboard'),
]
